# This file was generated based on the recommendations from https://docs.github.com/en/enterprise-cloud@latest/copilot/customizing-copilot/customizing-the-development-environment-for-copilot-coding-agent#preinstalling-tools-or-dependencies-in-copilots-environment

name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

env:
  EXAMPLES_FOLDER: examples

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code with submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: .
          version: "latest"

      - name: Install dependencies
        run: | 
          uv sync --dev

      - name: Set environment variables for Copilot
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          echo "PATH=$CONDA_PREFIX/bin:$PATH" >> $GITHUB_ENV
          echo "PATH=$PWD/.venv/bin:$PATH" >> $GITHUB_ENV
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV

      - name: Verify environment setup
        run: |
          echo "Python location: $(which python)"
          echo "Python path: $PYTHONPATH"
          python -c "import sys; print('Python sys.path:'); [print(f'  {p}') for p in sys.path]"